#  Stage 1: Build Stage

FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json tsconfig.json ./

RUN npm install

COPY . .

RUN npm run build

#  Stage 2: Production Stage

FROM node:22-alpine AS runner

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist
COPY .env.docker .env

EXPOSE 3000

CMD ["node", "dist/index.js"]
